from setuptools import setup, find_packages

setup(
    name='lnc',
    version='v1.0.0',
    packages=find_packages(),
    url='https://github.com/WhileEndless/LNC',
    license='GPL-3.0',
    author='Ahmetcan Akçay',
    author_email='ahmetcan1234akcay@gmail.com',
    description='LNC is a tool for crawl smb/ftp and extracting and analyzing files.',
    install_requires=[
        "blinker==1.8.2",
        "Brotli==1.1.0",
        "cffi==1.17.0",
        "charset-normalizer==3.3.2",
        "click==8.1.7",
        "cryptography==43.0.0",
        "dnspython==2.6.1",
        "dsinternals==1.2.4",
        "et-xmlfile==1.1.0",
        "Flask==3.0.3",
        "future==1.0.0",
        "impacket==0.11.0",
        "inflate64==1.0.0",
        "itsdangerous==2.2.0",
        "Jinja2==3.1.4",
        "ldap3==2.9.1",
        "ldapdomaindump==0.9.4",
        "lxml==5.3.0",
        "markdown-it-py==3.0.0",
        "MarkupSafe==2.1.5",
        "mdurl==0.1.2",
        "multivolumefile==0.2.3",
        "openpyxl==3.1.5",
        "pillow==10.4.0",
        "psutil==6.0.0",
        "py7zr==0.22.0",
        "pyasn1==0.6.0",
        "pybcj==1.0.2",
        "pycparser==2.22",
        "pycryptodomex==3.20.0",
        "Pygments==2.18.0",
        "PyMuPDF==1.24.9",
        "PyMuPDFb==1.24.9",
        "pyOpenSSL==24.2.1",
        "pyppmd==1.1.0",
        "python-docx==1.1.2",
        "PyYAML==6.0.2",
        "pyzstd==0.16.1",
        "rarfile==4.2",
        "rich==13.7.1",
        "six==1.16.0",
        "texttable==1.7.0",
        "typing_extensions==4.12.2",
        "Werkzeug==3.0.3"
    ],
    entry_points={
        'console_scripts': [
            'lnc = lnc.lnc:main'
        ]
    }
)
